/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    a = createFactory('a'),
    h2 = createFactory('h2'),
    li = createFactory('li'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

h2({"id": "CWDS-DesignOps"},
  "CWDS DesignOps",
),
ul({},
  li({},
    a({"href": "Experience-Values.md"},
      "Experience Values",
    ),
  ),
  li({},
    a({"href": "Human-centered-design.md"},
      "Human-centered design",
    ),
  ),
  li({},
    a({"href": "About-Child-Welfare/.md"},
      "About Child Welfare",
    ),
  ),
),
h2({"id": "ScrumBan"},
  "ScrumBan",
),
ul({},
  li({},
    a({"href": "DesignOps-Scrumban.md"},
      "DesignOps Scrumban",
    ),
  ),
  li({},
    a({"href": "How-we-work:-Definitions-of-Ready-and-Done.md"},
      "DesignOps Definition of Ready/Done",
    ),
  ),
  li({},
    a({"href": "Ceremonies.md,-Sessions-&-Communication-Channels"},
      "Ceremonies, Sessions, and Communication Channels",
    ),
  ),
  li({},
    a({"href": "Design-Review.md"},
      "Design Review",
    ),
  ),
),
h2({"id": "Component-Library"},
  "Component Library",
),
ul({},
  li({},
    a({"href": "component-library.md"},
      "Component Library",
    ),
  ),
  li({},
    a({"href": "Contribution-Guidelines.md"},
      "Contribution Guidelines",
    ),
  ),
  li({},
    a({"href": "Technical-Design-Brief.md"},
      "Technical Design Brief",
    ),
  ),
  li({},
    a({"href": "ux-ui-principles.md"},
      "UX/UI Principles",
    ),
  ),
  li({},
    a({"href": "Accessible-Design.md"},
      "Accessible Design",
    ),
  ),
  li({},
    a({"href": "content-strategy.md"},
      "Content Strategy",
    ),
  ),
  li({},
    a({"href": "Technology-Approach.md"},
      "Technology Approach",
    ),
  ),
),
h2({"id": "Research"},
  "Research",
),
ul({},
  li({},
    a({"href": "Discovery-Research.md"},
      "Conducting Discovery Research",
    ),
  ),
  li({},
    "Research Standards",
  ),
  li({},
    "Research Methods",
  ),
  li({},
    "Usability Testing",
  ),
),
h2({"id": "The-Team"},
  "The Team",
),
ul({},
  li({},
    a({"href": "Design-Team-Charter#purpose.md"},
      "Purpose",
    ),
  ),
  li({},
    a({"href": "Design-Team-Charter#focus.md"},
      "Focus",
    ),
  ),
  li({},
    a({"href": "Design-Team-Charter#perceive.md"},
      "Perception",
    ),
  ),
  li({},
    a({"href": "Design-Team-Charter#how-we-work.md"},
      "How we work",
    ),
  ),
  li({},
    a({"href": "Design-Team-Charter#how-to-work-with-us.md"},
      "How to work with us",
    ),
  ),
  li({},
    a({"href": "Tools.md"},
      "Tools",
    ),
  ),
)

  )
}
