/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    a = createFactory('a'),
    h2 = createFactory('h2'),
    li = createFactory('li'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

h2({"id": "CWDS-DesignOps"},
  "CWDS DesignOps",
),
ul({},
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki"},
      "Design Vision",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Experience-Values"},
      "Experience Values",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Human-centered-design"},
      "Human-centered design",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/About-Child-Welfare/"},
      "About Child Welfare",
    ),
  ),
),
h2({"id": "ScrumBan"},
  "ScrumBan",
),
ul({},
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/DesignOps-Scrumban"},
      "DesignOps Scrumban",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/How-we-work:-Definitions-of-Ready-and-Done"},
      "DesignOps Definition of Ready/Done",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Ceremonies,-Sessions-&-Communication-Channels"},
      "Ceremonies, Sessions, and Communication Channels",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Design-Review"},
      "Design Review",
    ),
  ),
),
h2({"id": "Component-Library"},
  "Component Library",
),
ul({},
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/component-library"},
      "Component Library",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Contribution-Guidelines"},
      "Contribution Guidelines",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Technical-Design-Brief"},
      "Technical Design Brief",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/ux-ui-principles"},
      "UX/UI Principles",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Accessible-Design"},
      "Accessible Design",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/content-strategy"},
      "Content Strategy",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Technology-Approach"},
      "Technology Approach",
    ),
  ),
),
h2({"id": "Research"},
  "Research",
),
ul({},
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Discovery-Research"},
      "Conducting Discovery Research",
    ),
  ),
  li({},
    "Research Standards",
  ),
  li({},
    "Research Methods",
  ),
  li({},
    "Usability Testing",
  ),
),
h2({"id": "The-Team"},
  "The Team",
),
ul({},
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Design-Team-Charter#purpose"},
      "Purpose",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Design-Team-Charter#focus"},
      "Focus",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Design-Team-Charter#perceive"},
      "Perception",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Design-Team-Charter#how-we-work"},
      "How we work",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Design-Team-Charter#how-to-work-with-us"},
      "How to work with us",
    ),
  ),
  li({},
    a({"href": "https://github.com/ca-cwds/research-design/wiki/Tools"},
      "Tools",
    ),
  ),
)

  )
}
