/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    a = createFactory('a'),
    code = createFactory('code'),
    h2 = createFactory('h2'),
    h3 = createFactory('h3'),
    li = createFactory('li'),
    p = createFactory('p'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

h2({"id": "Vision"},
  "Vision",
),
p({},
  "The living framework for our decisions and the way we communicate it to the entire organization. It provides us the ability to share and build upon our visual language, tone, components, and patterns.",
),
h2({"id": "Tools"},
  "Tools",
),
p({},
  "Currently, the ",
  a({"href": "https://ca-cwds.github.io/research-design/"},
    "initial version of our design system",
  ),
  " implemented with ",
  a({"href": "http://trulia.github.io/hologram/"},
    "Hologram",
  ),
  " is being migrated to ",
  a({"href": "https://ca-cwds.github.io/react-wood-duck/"},
    "the latest version of our design system",
  ),
  " implemented with ",
  a({"href": "https://storybook.js.org/"},
    "Storybook",
  ),
  ".",
),
h3({"id": "Goals"},
  "Goals",
),
ul({},
  li({},
    "Reuse",
  ),
  li({},
    "Scalability",
  ),
  li({},
    "Reduce duplication efforts across digital service teams",
  ),
  li({},
    "Contextual documentation",
  ),
  li({},
    "Inform best practices from design to development",
  ),
  li({},
    "Global components: Abstract when it’s right",
  ),
  li({},
    "Provide a path to support",
  ),
  li({},
    "Stray away from building (and managing) a product.",
  ),
  li({},
    "Build upon existing tools",
  ),
),
h3({"id": "Anti-Goals"},
  "Anti-Goals",
),
ul({},
  li({},
    "Build something from scratch",
  ),
  li({},
    "Don’t establish contribution guidelines",
  ),
  li({},
    "Don’t agree on a set of tools",
  ),
  li({},
    "Has lots of manual points that cause bottlenecks",
  ),
  li({},
    "Don’t update it",
  ),
  li({},
    "Don’t have a versioning methodology agreed upon",
  ),
),
h2({"id": "Why-a-component-library"},
  "Why a component library?",
),
ul({},
  li({},
    "Provides a consistent user experience across services, including look (CSS) and behavior (JS)",
  ),
  li({},
    "Maintains design clarity and quality by undergoing review to be added to the library",
  ),
  li({},
    "Makes design prototyping and development efficient and timely. Designers need not provide “pixel perfect specs” but instead draw from known components or better understand when to suggest a new one. Developers do not need to guess specifications but be pointed to the components to pull from the library.",
  ),
),
h2({"id": "Using-the-component-library"},
  "Using the component library",
),
p({},
  "Developers: if a design is not derived from master patterns or specifically suggesting new patterns be added, then the design should be rejected.\nDesigners: use patterns for wireframes, prototypes etc. [Coming: patterns templates to use in Illustrator, Sketch, etc]",
),
h2({"id": "ReferenceInspiration:"},
  "Reference/Inspiration:",
),
p({},
  "Government",
),
ul({},
  li({},
    a({"href": "https://standards.usa.gov/"},
      "US Web Design Standards",
    ),
  ),
  li({},
    a({"href": "https://www.gov.uk/service-manual/design"},
      "GDS/gov.uk",
    ),
  ),
),
p({},
  "Industry Examples",
),
ul({},
  li({},
    a({"href": "https://github.com/alexpate/awesome-design-systems"},
      "Github repository of excellent design systems",
    ),
  ),
  li({},
    a({"href": "https://ux.mailchimp.com/patterns"},
      "Mailchimp",
    ),
  ),
  li({},
    a({"href": "http://appnexus.github.io/lucid/#/"},
      "Appnexus",
    ),
  ),
  li({},
    a({"href": "http://styleguide.cfapps.io/"},
      "Pivotal UI",
    ),
  ),
  li({},
    a({"href": "https://design.cms.gov/"},
      "Design System",
    ),
  ),
),
p({},
  "Philosophy and Practice",
),
ul({},
  li({},
    a({"href": "http://atomicdesign.bradfrost.com/"},
      "Atomic Design",
    ),
  ),
),
h2({"id": "Internal"},
  "Internal",
),
p({},
  "Slack Channels",
),
ul({},
  li({},
    code({}, "#design-ops"),
  ),
  li({},
    code({}, "#front-end"),
  ),
),
p({},
  "Inventory of Design system components (view only)\n",
  a({"href": "https://docs.google.com/spreadsheets/d/1URyC2XGJJQB4CTNwB_3ty39TiEo0zNmv6OLOnYPQnZM/edit?usp=sharing"},
    "https://docs.google.com/spreadsheets/d/1URyC2XGJJQB4CTNwB_3ty39TiEo0zNmv6OLOnYPQnZM/edit?usp=sharing",
  ),
)

  )
}
