/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    a = createFactory('a'),
    h2 = createFactory('h2'),
    li = createFactory('li'),
    ol = createFactory('ol'),
    p = createFactory('p'),
    strong = createFactory('strong'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

h2({"id": "Purpose"},
  a({"href": "#purpose"},
    "Purpose",
  ),
),
p({},
  strong({},
    "DesignOps works with Product and Engineering to create effective user-centered solutions for CA Child Welfare Digital Services.",
  ),
),
p({},
  "We work collaboratively to ensure we create a flexible design system that allows all product teams move faster.",
),
p({},
  strong({},
    "DesignOps models how government can iteratively design and build user-centered, effective digital services.",
  ),
  "\nNot only do we deliver solutions for CWS-CARES, we model our process to our colleagues at CWDS, and all state and federal government.",
),
p({},
  "We work in the open and tell about our process, our wins, and our lessons learned.",
),
h2({"id": "Our-Focus"},
  a({"href": "#focus"},
    "Our Focus",
  ),
),
ul({},
  li({},
    "User Research",
  ),
  li({},
    "Information Architecture",
  ),
  li({},
    "Interaction Design",
  ),
  li({},
    "Content Design (coming)",
  ),
  li({},
    "Prototyping",
  ),
  li({},
    "Design systems",
  ),
  li({},
    "Usability Testing",
  ),
  li({},
    "Design education/outreach",
  ),
),
h2({"id": "How-we-work"},
  a({"href": "#how-we-work"},
    "How we work",
  ),
),
p({},
  "We:",
),
p({},
  strong({},
    "1. Make informed design decisions based on user research, usability testing, data insights, policy, and our professional experience.",
  ),
  "\nWe do the planning, research, and synthesis to understand our users’ needs, goals, and motivations. We share insights with the rest of our teams.",
),
p({},
  strong({},
    "2. Embrace meaningful design critique.",
  ),
  "\nWe meet regularly to share our work to get structured feedback. We are honest and open giving and receiving feedback. We are open to learning from each other and teaching what we know.",
),
p({},
  strong({},
    "3. Create spaces for exploration.",
  ),
  " \nWe are aware when we need to explore ideas. We frame problem spaces with quality prompts to foster creative thinking. We create structured or unstructured mental and physical spaces to explore ideas.",
),
p({},
  "We “steal smart.” We consider good solutions already in use before inventing our own.",
),
p({},
  "We help our product team and core constituent/stakeholders understand this as part of our process. We involve them when it will yield better ideas.",
),
p({},
  strong({},
    "4. Follow through on focus and decision making.",
  ),
  "\nWe hold ourselves accountable to follow through on deliverables. We respect the interdependencies with our product owners and developers. We use time boxing and a spirit of experimentation to help us move forward with decisions.",
),
p({},
  strong({},
    "5. Iterate and embrace fast failures.",
  ),
  "\nWe are not afraid to learn something didn’t work and improve it. We seek and respond to honest feedback.",
),
p({},
  "We use the agile sprint structure to build in retrospection, iteration and improvements.",
),
p({},
  strong({},
    "6. Validate our work through qualitative and quantitative research.",
  ),
  " \nWe hold regular research and/or design critiques with our core constituents and business team members. We perform ongoing research and usability testing to ensure continuous improvement. We study the data of the current system to understand our users’ past behavior and find opportunities to improve data quality going forward.",
),
p({},
  strong({},
    "7. Work in the open.",
  ),
  "  \nWe externalize our work in the CWDS office to encourage conversations and anchor decision making.",
),
p({},
  "We share insights with our development teams and help them understand the needs, goals and motivations of the users they code for.",
),
p({},
  "We share our work in progress for other teams and the public following this project to understand how we work and what we are delivering.",
),
p({},
  strong({},
    "8. Respect each others opinions and time.",
  ),
  " \nWe listen to each others reasoning and explanations. We run our sessions with clear goals. We come to meetings prepared and on time.",
),
p({},
  strong({},
    "9. Work cross-team as one research and design practice.",
  ),
  "\nRegardless of the different parts we work on, regardless of which contractor we are employed by, regardless of what we did before joining this project, we are one design team that collaborates to ensure we build a holistic, user-centered experience.",
),
p({},
  "We help our product teams understand we are building a design system that will serve user needs.",
),
h2({"id": "We-want-to-be-perceived-as..."},
  a({"href": "#perceive"},
    "We want to be perceived as…",
  ),
),
ul({},
  li({},
    "Trusted, experience design professionals who are respected for the work we do and the conversations we facilitate.",
  ),
  li({},
    "Informed by user research and data insights.",
  ),
  li({},
    "Collaborative with each other and our core state and county constituents.",
  ),
  li({},
    "Holistic design thinkers who can navigate parts to wholes.",
  ),
  li({},
    "Partners working equally with product/business and development.",
  ),
  li({},
    "One design discipline, regardless of contractor.",
  ),
  li({},
    "Valued as the “tip of the spear” that ensures development is invested in the right efforts.",
  ),
),
h2({"id": "How-to-work-with-us"},
  a({"href": "#how-to-work-with-us"},
    "How to work with us",
  ),
),
ol({},
  li({},
    p({},
      strong({},
        "Come to us with problems to solve, not solutions to implement.",
      ),
      " We are the stewards of user needs and approach our work as part of holistic design systems. Frame your problem as a user need OR ask us to discover the user need related to that problem.",
    ),
  ),
  li({},
    p({},
      "Ask us what ",
      strong({},
        "process",
      ),
      " we will use to address a problem. Ask us how you can support that.",
    ),
  ),
  li({},
    p({},
      strong({},
        "Give us the time and space to ask questions and explore solutions.",
      ),
      " Ask us how much time and space we need.",
    ),
  ),
  li({},
    p({},
      strong({},
        "Plan ahead.",
      ),
      " Remember that most research and design happens at least a sprint or two ahead of development work.",
    ),
  ),
  li({},
    p({},
      strong({},
        "Understand that design is iterative.",
      ),
      " The first thing you see is not always the final solution. With time to think strategically, we can design early stage solutions that we can all build on.",
    ),
  ),
  li({},
    p({},
      "Remember ",
      strong({},
        "usability testing and feedback sessions",
      ),
      " means further design improvements might need to be planned for.",
    ),
  ),
  li({},
    p({},
      strong({},
        "Participate in design reviews.",
      ),
      " Ask us “what user need are you addressing with that” and not “I don’t like it” Although we need to use systems thinking to build software, we need to map our priorities to user needs. Ask us our research and design process we used to come up with a proposed solution. Be aware if a design review is about exploring possibilities or refining a direction. Ask us what sort of user validation we need to move forward with a design decision.",
    ),
  ),
  li({},
    p({},
      strong({},
        "Embrace our colocated, agile, cross functional teams.",
      ),
      " Excessive redlining and documentation are not needed when we sit next to our developers. When the time comes, let us pair with developers to build easy to implement design systems.",
    ),
  ),
)

  )
}
