/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    a = createFactory('a'),
    h2 = createFactory('h2'),
    h3 = createFactory('h3'),
    li = createFactory('li'),
    ol = createFactory('ol'),
    p = createFactory('p'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

p({},
  "“Design critique”… “Review sessions”… “Feedback”…",
),
p({},
  "It goes by different names but in this context it is about structured feedback given by peers and stakeholders.",
),
p({},
  "Benefits:",
),
ul({},
  li({},
    "helps improve design standards and quality across the team",
  ),
  li({},
    "reduces silos among design, product and dev",
  ),
  li({},
    "increases awareness and encourages good discussion",
  ),
),
h2({"id": "Design-Review"},
  "Design Review",
),
ul({},
  li({},
    "Share out work in progress across teams",
  ),
  li({},
    "Review specific workflows, features. components, or research findings for cross-team feedback, awareness and alignment.",
  ),
  li({},
    "Roles: Facilitator, Presenter, Notetaker",
  ),
),
h2({"id": "Rules-of-engagement"},
  "Rules of engagement",
),
h3({"id": "For-Designers"},
  "For Designers",
),
ol({},
  li({},
    "Clearly state your goal and the context. Who is the user and what are their goals in the current scenario?",
  ),
  li({},
    "Briefly mention constraints and opportunities you considered.",
  ),
  li({},
    "Show something. Rallying around something visual decreases misunderstandings and helps get your ideas across.",
  ),
  li({},
    "Provide multiple solutions to unfamiliar problems.",
  ),
  li({},
    "State what type of feedback you need from the group. Consider your audience and what areas they can provide feedback in.",
  ),
  li({},
    "As you receive feedback, repeat it back to ensure you have heard it correctly. You can state that you will take it into consideration.",
  ),
  li({},
    "Avoid promising to incorporate every piece of feedback to please the room. Synthesize what you have heard and share what your next steps are and how you will or will not include feedback.",
  ),
  li({},
    "How is this design responsive? Has accessibility needs been accounted for (if applicable)?",
  ),
),
h3({"id": "For-Stakeholders-and-Peers"},
  "For Stakeholders and Peers",
),
ol({},
  li({},
    "Provide feedback in terms of goals met, not preferences (it’s not about what you “like” but what works for a task or other goal).",
  ),
  li({},
    "Prompt the presenter to provide context to work they present, never let a designer just say “do you like this?”",
  ),
  li({},
    "Be respectful, empathetic and candid.",
  ),
  li({},
    "Avoid trying to solve the problem for the designer. Instead ask clarifying questions.",
  ),
),
h2({"id": "Further-info"},
  "Further info",
),
ul({},
  li({},
    p({},
      a({"href": "https://medium.com/@suelynyu/a-practical-guide-to-running-effective-design-critiques-c6e8166c9eb0"},
        "https://medium.com/@suelynyu/a-practical-guide-to-running-effective-design-critiques-c6e8166c9eb0",
      ),
    ),
  ),
  li({},
    p({},
      a({"href": "https://designnotes.blog.gov.uk/2017/11/27/using-design-crits-to-improve-collaboration/"},
        "https://designnotes.blog.gov.uk/2017/11/27/using-design-crits-to-improve-collaboration/",
      ),
    ),
  ),
  li({},
    p({},
      "Org Design for Design Orgs, by Peter Merholz and Kristin Skinner (O’Reilly c 2016)",
    ),
  ),
)

  )
}
