/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    h3 = createFactory('h3'),
    li = createFactory('li'),
    p = createFactory('p'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

p({},
  "As we design CWS-CARES, we seek solutions that support the following experiences to workers. The following principles are based on user research and discussions with CWDS Service Managers. They are our design promise to our users.",
),
h3({"id": "Keep-the-child-at-the-center-not-the-system"},
  "Keep the child at the center, not the system",
),
ul({},
  li({},
    "Keep me focused on how the work I am doing right now benefits children",
  ),
  li({},
    "Show me how information and actions relate to the child I am serving",
  ),
  li({},
    "Let me spend as much time as possible with children and families",
  ),
  li({},
    "Spare me from repetitive and pointless tasks",
  ),
  li({},
    "Help me coordinate with others who are also working with my children",
  ),
),
h3({"id": "Use-data-to-make-informed-decisions"},
  "Use data to make informed decisions",
),
ul({},
  li({},
    "Guide me to enter data that is accurate and relevant",
  ),
  li({},
    "Let data tell a story that is meaningful and true",
  ),
  li({},
    "Allow me to fix inaccurate data",
  ),
  li({},
    "Integrate information from other systems so that I can see the whole picture",
  ),
  li({},
    "Show me relevant information",
  ),
),
h3({"id": "Allow-work-where-and-when-it-needs-to-be-done"},
  "Allow work where and when it needs to be done",
),
ul({},
  li({},
    "Make my fieldwork easy to do on any device",
  ),
  li({},
    "Give me access to information I need even when offline",
  ),
  li({},
    "Let me to do my work even if faced with a disability",
  ),
  li({},
    "Be reliable. Save my work",
  ),
  li({},
    "Reduce my reliance on paper",
  ),
),
h3({"id": "Connect-policy-and-practice.-Support-good-social-work"},
  "Connect policy and practice. Support good social work",
),
ul({},
  li({},
    "Capture patterns of actions and outcomes that tell a clear story for policy makers",
  ),
  li({},
    "Tell me how I am contributing to larger goals",
  ),
  li({},
    "Keep me in the bounds of the law and policy",
  ),
  li({},
    "Empower me to do more than the minimum required if it will improve outcomes",
  ),
),
h3({"id": "Cultivate-professionalism-trust-and-connectedness"},
  "Cultivate professionalism, trust, and connectedness",
),
ul({},
  li({},
    "Interact with me like the professional I am",
  ),
  li({},
    "Be trustworthy, fast, and accurate",
  ),
  li({},
    "Respond to my actions crisply",
  ),
  li({},
    "Make the next step clear and easy",
  ),
  li({},
    "Speak warmly and clearly to me",
  ),
)

  )
}
