/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    h1 = createFactory('h1'),
    h2 = createFactory('h2'),
    li = createFactory('li'),
    p = createFactory('p'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

h1({"id": "CWDS-CWS-CARES-Design-Vision"},
  "CWDS / CWS-CARES Design Vision",
),
h2({"id": "Background"},
  "Background",
),
p({},
  "The people working in the state, county, and tribal areas of CA are the people we entrust to respond to, protect, and maintain the safety, well being, and home permanency of CA’s at risk children. At Child Welfare Digital Services (CWDS) we are redesigning the tools that help these case workers, social workers, home approval and licensing workers, and administrative staff who do this work. When we increase the time social workers and other professionals interact with the children in the child welfare system, it leads to better outcomes for children. We aim to do that by designing more efficient tools.",
),
p({},
  "CWS-CARES will replace multiple, disjointed state and county systems currently in use, including the statewide CWS/Case Management System that was created in 1997.",
),
h2({"id": "Vision"},
  "Vision",
),
p({},
  "We will design solutions that that:",
),
ul({},
  li({},
    "Meet user needs based on primary user research and feedback from county and tribal workers",
  ),
  li({},
    "Address changing policy requirements",
  ),
  li({},
    "Improve the quality of data entered into the system",
  ),
),
p({},
  "CWS-CARES will be reliable, responsive, and intuitive to use. Workers will be able to better monitor the safety, well being and home permanency of children touched by the CA child welfare system.",
),
p({},
  "The design will encourage workers to identify and capture valuable information. It will allow both workers and policy makers to pull actionable insights from the data.",
),
p({},
  "The design will keep simple things simple and make complex things understandable.",
),
p({},
  "CWS-CARES will be one of the best child welfare decision-making tools in the nation. We will share the research insights that lead to our design decisions as well as resulting the principles, design system, and solutions. We invite other states to use and build on our work.",
),
p({},
  "We believe that government can build excellent user-centered digital services.",
),
h2({"id": "Goals"},
  "Goals",
),
ul({},
  li({},
    "Efficiency",
  ),
  li({},
    "Consistency",
  ),
  li({},
    "Foster Design System thinking",
  ),
  li({},
    "Continue to establish what’s there and what’s missing",
  ),
  li({},
    "Determine areas to contribute to the living framework\nwhere decisions live",
  ),
  li({},
    "Collect and document decisions in living framework",
  ),
  li({},
    "Provide priority of needs across design system\n(components, patterns, visual language, etc)",
  ),
  li({},
    "Establish a governance model",
  ),
  li({},
    "Include a voice from all service teams",
  ),
  li({},
    "Support Digital Service Teams",
  ),
  li({},
    "Maintain and foster growth of the design system",
  ),
)

  )
}
