/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    a = createFactory('a'),
    h2 = createFactory('h2'),
    li = createFactory('li'),
    p = createFactory('p'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

h2({"id": "Where-our-users-do-their-work"},
  "Where our users do their work",
),
p({},
  "CWDS state and county workers use equipment and have access to browsers determined either by their specific county IT department or by the state. They work from offices they work \nin the field\" visiting homes, they work from their parked car, they work while doing a visit from a hospital or courthouse.",
),
h2({"id": "Browser-Support"},
  "Browser Support",
),
p({},
  "Browser Priority 1 (Standards compliant)\n• WebKit\n     • Chrome\n     • Safari\n     • Edge\n• Gecko\n     • Firefox",
),
p({},
  "Browser Priority 2 (Non-Standards compliant) \n• Microsoft (Legacy)\n     • IE v11",
),
h2({"id": "Responsive-design-for-differing-devices"},
  "Responsive design for differing devices",
),
p({},
  "Counties and state offices provide different sizes and models of computer monitors, tablets, and smart phones to their workers.",
),
p({},
  "We are designing a responsive application that will:",
),
ul({},
  li({},
    "work best on common screen sizes",
  ),
  li({},
    "be responsive to smaller screen sizes by setting breakpoints for the display to optimize to the size detected\n*allow users to “zoom” the application while maintaining application coherence and clarity",
  ),
),
p({},
  "CWDS design will focus on optimized design for:",
),
ul({},
  li({},
    "Large-Desktops (1140px minimum)",
  ),
  li({},
    "Medium-Tablet (767 px)",
  ),
  li({},
    "Small-Mobile Device (450px)",
  ),
),
p({},
  "Later iterations will",
),
ul({},
  li({},
    "optimize application workflows for mobile and field work",
  ),
  li({},
    "design for on best display for “extra large” monitors such as 27 inch screens or projectors as the needs are identified from county request.",
  ),
),
h2({"id": "ScreenResolution"},
  "ScreenResolution",
),
p({},
  "Under Research",
),
h2({"id": "Resources"},
  "Resources",
),
p({},
  a({"href": "http://www.websitedimensions.com/"},
    "Websitedimensions.com",
  ),
)

  )
}
