/* eslint-disable */

const React = require('react').default || require('react')
const { createElement, createFactory } = require('react')

module.exports = function({ factories={} }) {
  const {
    a = createFactory('a'),
    h2 = createFactory('h2'),
    li = createFactory('li'),
    ol = createFactory('ol'),
    p = createFactory('p'),
    strong = createFactory('strong'),
    ul = createFactory('ul'),
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

h2({"id": "Background"},
  "Background",
),
p({},
  "DesignOps stories start life in the DesignOps backlog, but they are ",
  strong({},
    "moved",
  ),
  " to Digital Service (DS) Team backlogs during the ",
  a({"href": "https://github.com/ca-cwds/research-design/wiki/DesignOps-Story-Auction-(DOSA)"},
    strong({},
      "DesignOps Story Auction (DOSA)",
    ),
  ),
  ". This means in order to see all the DesignOps stories, you need to look across each of the DS team backlogs.",
),
h2({"id": "Workspaces-allow-you-to-view-stories-across-multiple-Pivotal-Trackers"},
  "Workspaces allow you to view stories across multiple Pivotal Trackers",
),
p({},
  "In order to see the DesignOps stories that live in the various DS team backlogs, a ",
  strong({},
    "workspace",
  ),
  " can be set up in Pivotal Tracker. Workspaces are essentially a view of multiple Pivotal Tracker projects, with searching that spans the projects in the workspace.",
),
h2({"id": "Create-Workspace"},
  "Create Workspace",
),
ol({},
  li({},
    "From an existing project, click on the title at the top-left to display menu of projects. At upper-right of the menu, click “Create Workspace”",
  ),
  li({},
    "From the dashboard, click on the Workspaces tab, and click on “Create Workspace” at upper-right.",
  ),
  li({},
    "Enter the name you want and click “Create”",
  ),
),
h2({"id": "Add-Projects-You-Want"},
  "Add Projects You Want",
),
ol({},
  li({},
    "On the left side of the workspace, click “Add Projects”",
  ),
  li({},
    "Click on “Choose Project to Add” and select a project you want in your workspace (Repeat for all projects you need)",
  ),
  li({},
    "Current projects needed:",
  ),
),
ul({},
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1655887"},
      strong({},
        "intake_dev",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1662141"},
      strong({},
        "CALS_dev",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1787975"},
      strong({},
        "Case Management",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1943385"},
      strong({},
        "Case Management_Design",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/2025809"},
      strong({},
        "Case Management_Dev",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1995543"},
      strong({},
        "Intake_Product",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1619261"},
      strong({},
        "Technology Platform.1",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/2034803"},
      strong({},
        "HOTLINE",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1577353"},
      strong({},
        "Web",
      ),
    ),
  ),
  li({},
    a({"href": "https://www.pivotaltracker.com/n/projects/1963189"},
      strong({},
        "Design-ops",
      ),
    ),
  ),
),
ol({"start": undefined},
  li({},
    "Reorder as needed. The order will dictate the order for search results, so having Design-ops at the bottom will keep the long list of icebox stories at the bottom.",
  ),
),
h2({"id": "View-DesignOps-Stories"},
  "View DesignOps Stories",
),
ol({},
  li({},
    "DesignOps stories are labelled with one of the following:",
  ),
),
ul({},
  li({},
    strong({},
      "design-ops",
    ),
    " (general)",
  ),
  li({},
    strong({},
      "design-ops design",
    ),
    " (design)",
  ),
  li({},
    strong({},
      "design-ops dev",
    ),
    " (development)",
  ),
),
ol({"start": undefined},
  li({},
    "Use the search bar at the top-right of Pivotal Tracker to search against all projects.",
  ),
  li({},
    "For DesignOps stories, include the following in search: “",
    strong({},
      "label:design-ops",
    ),
    "*” (Will find all design-ops stories). You can limit to design or development by using “",
    strong({},
      "label:design-ops design",
    ),
    "” or “",
    strong({},
      "label:design-ops dev",
    ),
    "”",
  ),
),
h2({"id": "Saving-a-search"},
  "Saving a search",
),
ol({},
  li({},
    "To save a search, you can click on the vertical ellipsis at the upper-right of the search results list and select “Pin search”",
  ),
  li({},
    "Pinned searches are refreshed each time the page is loaded, or you can click on the refresh (circle with arrow) icon at the upper-right of the search results. ",
    strong({},
      "NOTE:",
    ),
    " This differs from project panels, which are dynamically refreshed.",
  ),
),
h2({"id": "Setting-up-a-view-of-major-states-for-DesignOps-stories-(unscheduled-started-finished-delivered-accepted)"},
  "Setting up a view of major states for DesignOps stories (unscheduled, started, finished, delivered, accepted)",
),
ol({},
  li({},
    "Search for “",
    strong({},
      "state:unscheduled AND label:design-ops",
    ),
    "*”, then Pin the search",
  ),
  li({},
    "Search for “",
    strong({},
      "state:unstarted AND label:design-ops",
    ),
    "*”, then Pin the search",
  ),
  li({},
    "Search for “",
    strong({},
      "state:started AND label:design-ops",
    ),
    "*”, then Pin the search",
  ),
  li({},
    "Search for “",
    strong({},
      "state:finished AND label:design-ops",
    ),
    "*”, then Pin the search",
  ),
  li({},
    "Search for “",
    strong({},
      "state:delivered AND label:design-ops",
    ),
    "*”, then Pin the search",
  ),
  li({},
    "Search for “",
    strong({},
      "state:accepted AND label:design-ops",
    ),
    "*”, then Pin the search",
  ),
  li({},
    "Reorder the panels by clicking the title bar of the search results panel and drag it left or right",
  ),
)

  )
}
