import * as Reactstrap from './index'

describe('@cwds/reactstrap', () => {
  it.each`
    component
    ${'Badge'}
    ${'Breadcrumb'}
    ${'BreadcrumbItem'}
    ${'Button'}
    ${'ButtonDropdown'}
    ${'ButtonGroup'}
    ${'ButtonToolbar'}
    ${'Card'}
    ${'CardBody'}
    ${'CardDeck'}
    ${'CardFooter'}
    ${'CardHeader'}
    ${'Col'}
    ${'Collapse'}
    ${'Container'}
    ${'Dropdown'}
    ${'DropdownItem'}
    ${'DropdownMenu'}
    ${'DropdownToggle'}
    ${'Fade'}
    ${'Form'}
    ${'FormFeedback'}
    ${'FormGroup'}
    ${'FormText'}
    ${'Input'}
    ${'InputGroup'}
    ${'InputGroupAddon'}
    ${'Label'}
    ${'ListGroup'}
    ${'ListGroupItem'}
    ${'ListGroupItemHeading'}
    ${'ListGroupItemText'}
    ${'Modal'}
    ${'ModalBody'}
    ${'ModalFooter'}
    ${'ModalHeader'}
    ${'Nav'}
    ${'NavItem'}
    ${'NavLink'}
    ${'Popover'}
    ${'PopoverBody'}
    ${'PopoverContent'}
    ${'PopoverHeader'}
    ${'PopoverTitle'}
    ${'Progress'}
    ${'Row'}
    ${'Table'}
    ${'Tooltip'}
    ${'UncontrolledAlert'}
    ${'UncontrolledButtonDropdown'}
    ${'UncontrolledDropdown'}
    ${'UncontrolledTooltip'}
  `('exports $component', ({ component }) => {
    expect(Reactstrap[component]).toBeDefined()
  })
})
